name: DEICODE
channels:
- !!python/unicode
  'etetoolkit'
- !!python/unicode
  'omnia'
- !!python/unicode
  'bioconda'
- !!python/unicode
  'magonser'
- !!python/unicode
  'conda-forge'
- !!python/unicode
  'anaconda'
- !!python/unicode
  'defaults'
dependencies:
- !!python/unicode
  'cvxopt=1.1.8=py35_4'
- !!python/unicode
  'mkl=2017.0.1=0'
- !!python/unicode
  'nose=1.3.7=py35_1'
- !!python/unicode
  'numexpr=2.6.1=np111py35_2'
- !!python/unicode
  'numpy=1.11.3=py35_0'
- !!python/unicode
  'scikit-bio=0.5.1=np111py35_0'
- !!python/unicode
  'scikit-learn=0.18.1=np111py35_1'
- !!python/unicode
  'scipy=0.18.1=np111py35_1'
- !!python/unicode
  'seaborn=0.7.1=py35_0'
- !!python/unicode
  'biom-format=2.1.5=py35_3'
- !!python/unicode
  'brewer2mpl=1.4.1=py35_2'
- !!python/unicode
  'mock=2.0.0=py35_0'
- !!python/unicode
  'pbr=1.10.0=py35_0'
- !!python/unicode
  'protobuf=3.1.0=py35_0'
- !!python/unicode
  'tensorflow=0.12.1=py35_1'
- !!python/unicode
  '_license=1.1=py35_1'
- !!python/unicode
  '_nb_ext_conf=0.3.0=py35_0'
- !!python/unicode
  'alabaster=0.7.9=py35_0'
- !!python/unicode
  'anaconda-clean=1.0.0=py35_0'
- !!python/unicode
  'anaconda-client=1.5.1=py35_0'
- !!python/unicode
  'anaconda=custom=py35_0'
- !!python/unicode
  'anaconda-navigator=1.2.3=py35_0'
- !!python/unicode
  'appnope=0.1.0=py35_0'
- !!python/unicode
  'appscript=1.0.1=py35_0'
- !!python/unicode
  'argcomplete=1.0.0=py35_1'
- !!python/unicode
  'astroid=1.4.7=py35_0'
- !!python/unicode
  'astropy=1.2.1=np111py35_0'
- !!python/unicode
  'babel=2.3.4=py35_0'
- !!python/unicode
  'backports=1.0=py35_0'
- !!python/unicode
  'beautifulsoup4=4.5.1=py35_0'
- !!python/unicode
  'bitarray=0.8.1=py35_0'
- !!python/unicode
  'blaze=0.10.1=py35_0'
- !!python/unicode
  'bokeh=0.12.2=py35_0'
- !!python/unicode
  'boto=2.42.0=py35_0'
- !!python/unicode
  'bottleneck=1.1.0=np111py35_0'
- !!python/unicode
  'cachecontrol=0.11.7=py35_0'
- !!python/unicode
  'cffi=1.7.0=py35_0'
- !!python/unicode
  'chest=0.2.3=py35_0'
- !!python/unicode
  'click=6.6=py35_0'
- !!python/unicode
  'cloudpickle=0.2.1=py35_0'
- !!python/unicode
  'clyent=1.2.2=py35_0'
- !!python/unicode
  'colorama=0.3.7=py35_0'
- !!python/unicode
  'configobj=5.0.6=py35_0'
- !!python/unicode
  'contextlib2=0.5.3=py35_0'
- !!python/unicode
  'cryptography=1.5=py35_0'
- !!python/unicode
  'curl=7.49.0=1'
- !!python/unicode
  'cycler=0.10.0=py35_0'
- !!python/unicode
  'cython=0.24.1=py35_0'
- !!python/unicode
  'cytoolz=0.8.0=py35_0'
- !!python/unicode
  'dask=0.11.0=py35_0'
- !!python/unicode
  'datashape=0.5.2=py35_0'
- !!python/unicode
  'decorator=4.0.10=py35_0'
- !!python/unicode
  'dill=0.2.5=py35_0'
- !!python/unicode
  'docutils=0.12=py35_2'
- !!python/unicode
  'dynd-python=0.7.2=py35_0'
- !!python/unicode
  'entrypoints=0.2.2=py35_0'
- !!python/unicode
  'et_xmlfile=1.0.1=py35_0'
- !!python/unicode
  'fastcache=1.0.2=py35_1'
- !!python/unicode
  'filelock=2.0.6=py35_0'
- !!python/unicode
  'flask=0.11.1=py35_0'
- !!python/unicode
  'flask-cors=2.1.2=py35_0'
- !!python/unicode
  'freetype=2.5.5=1'
- !!python/unicode
  'future=0.16.0=py35_1'
- !!python/unicode
  'get_terminal_size=1.0.0=py35_0'
- !!python/unicode
  'gevent=1.1.2=py35_0'
- !!python/unicode
  'greenlet=0.4.10=py35_0'
- !!python/unicode
  'h5py=2.6.0=np111py35_2'
- !!python/unicode
  'hdf5=1.8.17=1'
- !!python/unicode
  'heapdict=1.0.0=py35_1'
- !!python/unicode
  'icu=54.1=0'
- !!python/unicode
  'idna=2.1=py35_0'
- !!python/unicode
  'imagesize=0.7.1=py35_0'
- !!python/unicode
  'ipykernel=4.5.0=py35_0'
- !!python/unicode
  'ipython=5.1.0=py35_0'
- !!python/unicode
  'ipython_genutils=0.1.0=py35_0'
- !!python/unicode
  'ipywidgets=5.2.2=py35_0'
- !!python/unicode
  'itsdangerous=0.24=py35_0'
- !!python/unicode
  'jbig=2.1=0'
- !!python/unicode
  'jdcal=1.2=py35_1'
- !!python/unicode
  'jedi=0.9.0=py35_1'
- !!python/unicode
  'jinja2=2.8=py35_1'
- !!python/unicode
  'jpeg=8d=2'
- !!python/unicode
  'jsonschema=2.5.1=py35_0'
- !!python/unicode
  'jupyter=1.0.0=py35_3'
- !!python/unicode
  'jupyter_client=4.4.0=py35_0'
- !!python/unicode
  'jupyter_console=5.0.0=py35_0'
- !!python/unicode
  'jupyter_core=4.2.0=py35_0'
- !!python/unicode
  'lazy-object-proxy=1.2.1=py35_0'
- !!python/unicode
  'libdynd=0.7.2=0'
- !!python/unicode
  'libpng=1.6.22=0'
- !!python/unicode
  'libtiff=4.0.6=2'
- !!python/unicode
  'libxml2=2.9.2=0'
- !!python/unicode
  'libxslt=1.1.28=2'
- !!python/unicode
  'llvmlite=0.13.0=py35_0'
- !!python/unicode
  'locket=0.2.0=py35_1'
- !!python/unicode
  'lockfile=0.12.2=py35_0'
- !!python/unicode
  'lxml=3.6.4=py35_0'
- !!python/unicode
  'markupsafe=0.23=py35_2'
- !!python/unicode
  'matplotlib=1.5.1=np111py35_0'
- !!python/unicode
  'mistune=0.7.3=py35_1'
- !!python/unicode
  'mkl-service=1.1.2=py35_2'
- !!python/unicode
  'mpmath=0.19=py35_1'
- !!python/unicode
  'multipledispatch=0.4.8=py35_0'
- !!python/unicode
  'natsort=5.0.1=py35_0'
- !!python/unicode
  'nb_anacondacloud=1.2.0=py35_0'
- !!python/unicode
  'nb_conda=2.0.0=py35_0'
- !!python/unicode
  'nb_conda_kernels=2.0.0=py35_0'
- !!python/unicode
  'nbconvert=4.2.0=py35_0'
- !!python/unicode
  'nbformat=4.1.0=py35_0'
- !!python/unicode
  'nbpresent=3.0.2=py35_0'
- !!python/unicode
  'networkx=1.11=py35_0'
- !!python/unicode
  'nltk=3.2.1=py35_0'
- !!python/unicode
  'notebook=4.2.3=py35_0'
- !!python/unicode
  'numba=0.28.1=np111py35_0'
- !!python/unicode
  'odo=0.5.0=py35_1'
- !!python/unicode
  'openpyxl=2.3.2=py35_0'
- !!python/unicode
  'openssl=1.0.2j=0'
- !!python/unicode
  'pandas=0.18.1=np111py35_0'
- !!python/unicode
  'partd=0.3.6=py35_0'
- !!python/unicode
  'path.py=8.2.1=py35_0'
- !!python/unicode
  'pathlib2=2.1.0=py35_0'
- !!python/unicode
  'patsy=0.4.1=py35_0'
- !!python/unicode
  'pep8=1.7.0=py35_0'
- !!python/unicode
  'pexpect=4.0.1=py35_0'
- !!python/unicode
  'pickleshare=0.7.4=py35_0'
- !!python/unicode
  'pillow=3.3.1=py35_0'
- !!python/unicode
  'pip=8.1.2=py35_0'
- !!python/unicode
  'pkginfo=1.3.2=py35_0'
- !!python/unicode
  'plac=0.9.6=py35_0'
- !!python/unicode
  'ply=3.9=py35_0'
- !!python/unicode
  'prompt_toolkit=1.0.3=py35_0'
- !!python/unicode
  'psutil=4.3.1=py35_0'
- !!python/unicode
  'ptyprocess=0.5.1=py35_0'
- !!python/unicode
  'py=1.4.31=py35_0'
- !!python/unicode
  'pyasn1=0.1.9=py35_0'
- !!python/unicode
  'pycosat=0.6.1=py35_1'
- !!python/unicode
  'pycparser=2.14=py35_1'
- !!python/unicode
  'pycrypto=2.6.1=py35_4'
- !!python/unicode
  'pycurl=7.43.0=py35_0'
- !!python/unicode
  'pyflakes=1.3.0=py35_0'
- !!python/unicode
  'pygments=2.1.3=py35_0'
- !!python/unicode
  'pylint=1.5.4=py35_1'
- !!python/unicode
  'pyopenssl=16.0.0=py35_0'
- !!python/unicode
  'pyparsing=2.1.4=py35_0'
- !!python/unicode
  'pyqt=4.11.4=py35_4'
- !!python/unicode
  'pytables=3.2.3.1=np111py35_0'
- !!python/unicode
  'pytest=2.9.2=py35_0'
- !!python/unicode
  'python=3.5.2=0'
- !!python/unicode
  'python-dateutil=2.5.3=py35_0'
- !!python/unicode
  'python.app=1.2=py35_4'
- !!python/unicode
  'pytz=2016.6.1=py35_0'
- !!python/unicode
  'pyyaml=3.12=py35_0'
- !!python/unicode
  'pyzmq=15.4.0=py35_0'
- !!python/unicode
  'qt=4.8.7=4'
- !!python/unicode
  'qtawesome=0.3.3=py35_0'
- !!python/unicode
  'qtconsole=4.2.1=py35_0'
- !!python/unicode
  'qtpy=1.1.2=py35_0'
- !!python/unicode
  'readline=6.2=2'
- !!python/unicode
  'redis=3.2.0=0'
- !!python/unicode
  'redis-py=2.10.5=py35_0'
- !!python/unicode
  'requests=2.11.1=py35_0'
- !!python/unicode
  'rope=0.9.4=py35_1'
- !!python/unicode
  'scikit-image=0.12.3=np111py35_1'
- !!python/unicode
  'setuptools=27.2.0=py35_0'
- !!python/unicode
  'simplegeneric=0.8.1=py35_1'
- !!python/unicode
  'singledispatch=3.4.0.3=py35_0'
- !!python/unicode
  'sip=4.18=py35_0'
- !!python/unicode
  'six=1.10.0=py35_0'
- !!python/unicode
  'snowballstemmer=1.2.1=py35_0'
- !!python/unicode
  'sockjs-tornado=1.0.3=py35_0'
- !!python/unicode
  'sphinx=1.4.6=py35_0'
- !!python/unicode
  'spyder=3.0.2=py35_0'
- !!python/unicode
  'sqlalchemy=1.0.13=py35_0'
- !!python/unicode
  'sqlite=3.13.0=0'
- !!python/unicode
  'statsmodels=0.6.1=np111py35_1'
- !!python/unicode
  'sympy=1.0=py35_0'
- !!python/unicode
  'terminado=0.6=py35_0'
- !!python/unicode
  'tk=8.5.18=0'
- !!python/unicode
  'toolz=0.8.0=py35_0'
- !!python/unicode
  'tornado=4.4.1=py35_0'
- !!python/unicode
  'traitlets=4.3.0=py35_0'
- !!python/unicode
  'unicodecsv=0.14.1=py35_0'
- !!python/unicode
  'wcwidth=0.1.7=py35_0'
- !!python/unicode
  'werkzeug=0.11.11=py35_0'
- !!python/unicode
  'wheel=0.29.0=py35_0'
- !!python/unicode
  'widgetsnbextension=1.2.6=py35_0'
- !!python/unicode
  'wrapt=1.10.6=py35_0'
- !!python/unicode
  'xlrd=1.0.0=py35_0'
- !!python/unicode
  'xlsxwriter=0.9.3=py35_0'
- !!python/unicode
  'xlwings=0.10.0=py35_0'
- !!python/unicode
  'xlwt=1.1.2=py35_0'
- !!python/unicode
  'xz=5.2.2=0'
- !!python/unicode
  'yaml=0.1.6=0'
- !!python/unicode
  'zlib=1.2.8=3'
- !!python/unicode
  'ete3=3.0.0b36=py_0'
- !!python/unicode
  'climate=0.4.6=py35_0'
- !!python/unicode
  'downhill=0.3.2=py35_0'
- !!python/unicode
  'theano=0.7.0=py35_0'
- !!python/unicode
  'cvxcanon=0.0.21=np111py35_0'
- !!python/unicode
  'cvxpy=0.3.1=py35_0'
- !!python/unicode
  'ecos=2.0.4=np111py35_0'
- !!python/unicode
  'scs=1.2.6=np111py35_1'
- pip:
  - backports.shutil-get-terminal-size==1.0.0
  - dynd==0.7.3.dev1
  - et-xmlfile==1.0.1
  - fancyimpute==0.1.0
  - gneiss==0.2.1
  - ipython-genutils==0.1.0
  - jupyter-client==4.4.0
  - jupyter-console==5.0.0
  - jupyter-core==4.2.0
  - keras==1.2.1
  - knnimpute==0.0.1
  - nb-anacondacloud==1.2.0
  - nb-conda==2.0.0
  - nb-conda-kernels==2.0.0
  - prompt-toolkit==1.0.3
  - rope-py3k==0.9.4.post1
  - tables==3.2.3.1
  - wpca==0.1
prefix: !!python/unicode '/Users/cameronmartino/anaconda/envs/DEICODE'

